### ISSUE TITLE
Error in BZSL-Python demo using dataset "INSECT"

### ISSUE THREAD

**Issue by saraelshawa** [sbadirli/Fine-Grained-ZSL-with-DNA#1]
If I run the following code: 
`python Demo.py --dataset INSECT --side_info dna`

I get the following error: 
``` 
Traceback (most recent call last):
  File "Demo.py", line 20, in <module>
    model.train_and_eval()
  File "../Fine-Grained-ZSL-with-DNA/BZSL-Python/bayesian_model.py", line 245, in train_and_eval
    dataloader = data_loader(self.datapath, self.dataset, self.side_info, self.tuning)
  File "../Fine-Grained-ZSL-with-DNA/BZSL-Python/utils.py", line 17, in __init__
    self.read_matdata()
  File "../Fine-Grained-ZSL-with-DNA/BZSL-Python/utils.py", line 47, in read_matdata
    self.side_info = splits_mat['att_dna']
KeyError: 'att_dna' 
```
This error doesn't seem to happen when using the CUB dataset. 

Any help would be appreciated, thanks!

**Comment by saraelshawa** [comment]
It looks like the `att_splits.mat` file for the INSECT dataset has a missing key comparing it to `att_splits.mat`  file for the CUB dataset. 

```
>>> import scipy.io as sio
>>> splits_mat = sio.loadmat("../data/CUB/att_splits.mat")
>>> splits_mat.keys()
dict_keys(['__header__', '__version__', '__globals__', 'allclasses_names', 'att', 'att_dna', 'att_w2v', 'original_att', 'test', 'test_seen_loc', 'test_unseen_loc', 'train', 'train_loc', 'trainval_loc', 'val_loc'])
>>> splits_mat = sio.loadmat("../data/INSECT/att_splits.mat")
>>> splits_mat.keys()
dict_keys(['__header__', '__version__', '__globals__', 'att', 'test_seen_loc', 'test_unseen_loc', 'train_loc', 'trainval_loc', 'val_loc', 'train', 'test'])
```

**Comment by sbadirli** [comment]
Hey Sara,

It is a typo I forgot, thanks for bringing it to my attention. CUB dataset has 3 different attributes but INSECT has only one with DNA and I name as 'att' but should have been 'att_dna'. You will need to rename the 'att' in INSECT splits_mat with 'att_dna'. 

I will update the repo in the weekend. In the meantime let me know if it solves your problem.

**Comment by sbadirli** [comment]
I did a quick fix. You don't need to change anything. Just fork/ download the repo again and it should work this time.

**Comment by saraelshawa** [comment]
Thanks for the fix and prompt response!
